### ISSUE TITLE
CI: test changes in hybrid SDK samples

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#5234]
### Description

- [ ] react native
- [ ] flutter
- [ ] .NET

**Comment by buenaflor** [comment]
For Flutter we have some native ios tests in `flutter/example/ios`: 

the steps to build the sample would be
- install flutter:
```yml
- name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: stable
```
- clone the repo
- run `flutter pub get` in `flutter/example`
